"""First-run setup helpers. `exo setup spoke` writes a capture-only
config.yaml for a new machine: role/device names set, secrets kept minimal —
a spoke gets the sync passphrase (to encrypt its outbound queue) and NOTHING
else: no Telegram token, no LLM keys (a spoke never calls a model)."""

from __future__ import annotations

import yaml

from ..config import REPO_ROOT, Config


def setup_spoke(cfg: Config, device: str, hub: str) -> str:
    target = REPO_ROOT / "config.yaml"
    if target.exists():
        return (f"{target} already exists — refusing to overwrite a live"
                " config. Edit it by hand (set role: spoke, device_name:"
                f" {device}) or move it away and re-run.")
    example = REPO_ROOT / "config.example.yaml"
    if not example.exists():
        return "config.example.yaml is missing — copy the repo again."

    data = yaml.safe_load(example.read_text(encoding="utf-8")) or {}
    device = device.strip()
    if device.casefold() == (hub.strip() or "").casefold():
        return ("device and hub must have DIFFERENT names — event ids are"
                " namespaced by device name, and the hub refuses batches"
                " claiming its own name.")
    data["role"] = "spoke"
    data["device_name"] = device
    data["hub_name"] = hub.strip() or "the-hub"
    # spokes hold no bot token — the one bot lives on the hub
    data.setdefault("telegram", {})
    data["telegram"]["bot_token"] = ""
    data["telegram"]["chat_id"] = ""
    # per-device allowlist, fail-closed until the user names real paths
    data["capture_code_from"] = {device: ["e:/CHANGE-ME-your-personal-projects"]}

    header = (
        "# Spoke config generated by `exo setup spoke` — capture-only machine.\n"
        "# 1. EDIT capture_code_from: real personal-project folders for THIS\n"
        "#    machine (employer work stays outside these paths = never read).\n"
        "# 2. Set the sync passphrase (same one as the hub): either the env\n"
        "#    var below or inline.\n"
        "# 3. Set sync.remote to the SAME rclone remote as the hub\n"
        "#    (install rclone + `rclone config` first), or leave empty and\n"
        "#    move batch files by hand.\n"
    )
    target.write_text(header + yaml.safe_dump(data, sort_keys=False,
                                              allow_unicode=True),
                      encoding="utf-8", newline="\n")
    return "\n".join([
        f"wrote {target} (role: spoke, device: {device})",
        "",
        "Next steps on this machine:",
        "  1. Edit config.yaml → capture_code_from: put this machine's real",
        "     personal-project folders (it captures NOTHING until you do).",
        "  2. Set the sync passphrase (same as the hub's) — env var or inline.",
        "  3. Install rclone (https://rclone.org/install/), run `rclone config`",
        "     to add the same remote as the hub, set sync.remote in config.yaml.",
        "  4. exo install --apply    (registers daemon-at-logon + daily queue push)",
        "  5. exo log \"hello from this machine\" ; exo sync push   (smoke test —",
        "     then run `exo sync merge` + `exo devices` on the hub to see it land)",
    ])
